Repository ProjectInTheClass/GasaOK, pull requests merged in 2022-10, with the labels that each got.

#84 보관함 빈 화면에서 검색으로 바로이동 구현 및 함수명 변경
  가사오케/GasaOK/Controller/SongFolder/ViewController.swift
  가사오케/GasaOK/View/Base.lproj/Main.storyboard
Labels: UI🎨

#83 [View] #82 : UISearchController 주석 처리, SearchBar, Button 넣기, Delegate 설정
  가사오케/GasaOK/Controller/Search/SearchVC.swift
  가사오케/GasaOK/View/Base.lproj/Main.storyboard
Labels: UI🎨

#86 [Feat] #85 Search Filter Button 추가
  가사오케/GasaOK/Controller/Search/SearchTableViewCell.swift
  가사오케/GasaOK/Controller/Search/SearchVC.swift
  가사오케/GasaOK/View/Base.lproj/Main.storyboard
Labels: feat✨, UI🎨

#89 [UI] #49: 보관함화면이 비어있을때 알림창 띄우기 및 검색으로 이동 버튼 구현 완료 및 오토레이아웃 설정 완료
  가사오케/GasaOK/Controller/SongFolder/ViewController.swift
  가사오케/GasaOK/View/Base.lproj/Main.storyboard
Labels: UI🎨

#88 [Feat] #87 : 버튼 모양 변경 및 메뉴 표시
  가사오케/GasaOK/Controller/Search/SearchTableViewCell.swift
  가사오케/GasaOK/View/Base.lproj/Main.storyboard
Labels: feat✨

#90 [feat] #85 : 전체 검색 완료
  가사오케/GasaOK/Controller/Search/SearchVC.swift
Labels: feat✨

#91 [Feat] #87 closed : 메뉴 항목 내 노래 추가 및 노래 가사 보기 구현 완료
  가사오케/GasaOK/Controller/Search/SearchTableViewCell.swift
  가사오케/GasaOK/Controller/Search/SearchVC.swift
  가사오케/GasaOK/Controller/SongFolder/ViewController.swift
Labels: feat✨
